"""
Turns the translated explanation into a downloadable PDF, styled to
match the app's own look (coral accent, deep plum) instead of a bare
default document. Every page gets a branded header band and a footer
with the page number and generation date; each medicine gets its own
card instead of a plain text line.

reportlab's built-in fonts don't have Indic glyphs, so each language
gets its own Noto font registered from the fonts/ folder - without this,
Hindi/Tamil/etc. text would render as blank boxes.

The LLM's explanation comes back with markdown (**bold**, * bullets) in
it, but reportlab's Paragraph doesn't understand markdown - it uses its
own limited HTML-like tags (<b>, <br/>, etc.). Without converting one to
the other, the PDF would show literal asterisks instead of bold text.
"""
import re
from datetime import datetime
from xml.sax.saxutils import escape

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable,
)

import config

_registered = set()

# Same palette as the app's own theme.py, so the PDF doesn't look like a
# different product from the app that generated it.
_ACCENT = colors.HexColor("#FF6B54")
_DARK = colors.HexColor("#241B33")
_CARD_BG = colors.HexColor("#FBEFEC")
_TEXT = colors.HexColor("#2A2A2A")
_MUTED = colors.HexColor("#7A7A7A")


def _font_for(language: str) -> str:
    """Registers the right font for this language (once) and returns
    its name for use in a paragraph style."""
    font_path = config.LANGUAGES.get(language, {}).get("font")
    if not font_path:
        return "Helvetica"  # English - built-in font is fine

    font_name = f"Noto-{language}"
    if font_name not in _registered:
        pdfmetrics.registerFont(TTFont(font_name, font_path))
        _registered.add(font_name)
    return font_name


def _markdown_to_reportlab(text: str) -> str:
    """Converts the LLM's markdown into reportlab's mini-markup, and
    escapes anything that would otherwise break its XML-ish parser.
    Order matters: escape first (so a literal '<' in the text can't be
    mistaken for a tag), THEN add our own <b> and <br/> tags."""
    text = escape(text)
    text = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", text)
    lines = [re.sub(r"^\*\s+", "\u2022 ", line) for line in text.split("\n")]
    return "<br/>".join(lines)


def _header_footer(canvas, doc):
    """Draws the branded header band and footer on every page. reportlab
    calls this once per page via SimpleDocTemplate's onPage hook."""
    canvas.saveState()
    width, height = A4

    # Header band
    canvas.setFillColor(_DARK)
    canvas.rect(0, height - 22 * mm, width, 22 * mm, fill=1, stroke=0)

    # Simple pill/capsule mark - two overlapping rounded shapes, drawn
    # directly rather than relying on emoji glyph support in the PDF font
    canvas.setFillColor(_ACCENT)
    canvas.roundRect(20 * mm, height - 15 * mm, 10 * mm, 5 * mm, 2.5 * mm, fill=1, stroke=0)
    canvas.setFillColor(colors.white)
    canvas.roundRect(24 * mm, height - 15 * mm, 6 * mm, 5 * mm, 2.5 * mm, fill=1, stroke=0)

    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 16)
    canvas.drawString(35 * mm, height - 14 * mm, "PresciMate")
    canvas.setFont("Helvetica", 9)
    canvas.setFillColor(colors.HexColor("#D8CFE0"))
    canvas.drawString(35 * mm, height - 19 * mm, "Your prescription, explained")

    # Footer
    canvas.setFillColor(_MUTED)
    canvas.setFont("Helvetica", 8)
    canvas.drawString(20 * mm, 12 * mm, f"Generated by PresciMate on {datetime.now().strftime('%d %b %Y')}")
    canvas.drawRightString(width - 20 * mm, 12 * mm, f"Page {doc.page}")

    canvas.restoreState()


def build_pdf(output_path: str, medicines: list[dict], explanation: str, language: str):
    font_name = _font_for(language)

    styles = getSampleStyleSheet()
    heading_style = ParagraphStyle(
        "SectionHeading", parent=styles["Heading2"], fontName=font_name,
        textColor=_DARK, spaceBefore=6, spaceAfter=4,
    )
    body_style = ParagraphStyle(
        "Body2", parent=styles["Normal"], fontName=font_name, leading=18,
        textColor=_TEXT, fontSize=10.5,
    )
    med_name_style = ParagraphStyle(
        "MedName", parent=styles["Normal"], fontName=font_name,
        textColor=_DARK, fontSize=12, leading=15,
    )
    med_detail_style = ParagraphStyle(
        "MedDetail", parent=styles["Normal"], fontName=font_name,
        textColor=_MUTED, fontSize=9.5, leading=13,
    )
    disclaimer_style = ParagraphStyle(
        "Disclaimer", parent=styles["Normal"], fontName=font_name,
        textColor=_TEXT, fontSize=8.5, leading=13,
    )

    doc = SimpleDocTemplate(
        output_path, pagesize=A4,
        topMargin=32 * mm, bottomMargin=22 * mm, leftMargin=20 * mm, rightMargin=20 * mm,
    )
    story = []

    # ---- Medicines section: each drug as its own card ----
    story.append(Paragraph("Your medicines", heading_style))
    story.append(HRFlowable(width="100%", thickness=1.2, color=_ACCENT, spaceAfter=10))

    for m in medicines:
        detail_bits = [b for b in [m.get("dosage"), m.get("frequency"), m.get("duration")] if b]
        detail_line = "  \u2022  ".join(escape(b) for b in detail_bits) or "Dosage not specified - confirm with your doctor"
        instructions = f"<br/>{escape(m['instructions'])}" if m.get("instructions") else ""

        card_content = [
            Paragraph(escape(m["name"]), med_name_style),
            Paragraph(detail_line + instructions, med_detail_style),
        ]
        card = Table([[card_content]], colWidths=[doc.width])
        card.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), _CARD_BG),
            ("LINEBEFORE", (0, 0), (0, -1), 3, _ACCENT),
            ("LEFTPADDING", (0, 0), (-1, -1), 14),
            ("RIGHTPADDING", (0, 0), (-1, -1), 14),
            ("TOPPADDING", (0, 0), (-1, -1), 10),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ]))
        story.append(card)
        story.append(Spacer(1, 8))

    story.append(Spacer(1, 10))

    # ---- Explanation section ----
    story.append(Paragraph("What this means for you", heading_style))
    story.append(HRFlowable(width="100%", thickness=1.2, color=_ACCENT, spaceAfter=10))

    for paragraph in explanation.split("\n\n"):
        if paragraph.strip():
            story.append(Paragraph(_markdown_to_reportlab(paragraph), body_style))
            story.append(Spacer(1, 8))

    # ---- Disclaimer ----
    story.append(Spacer(1, 12))
    disclaimer_table = Table([[Paragraph(escape(config.DISCLAIMER), disclaimer_style)]], colWidths=[doc.width])
    disclaimer_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F5F0E8")),
        ("LINEBEFORE", (0, 0), (0, -1), 3, colors.HexColor("#D9A441")),
        ("LEFTPADDING", (0, 0), (-1, -1), 14),
        ("RIGHTPADDING", (0, 0), (-1, -1), 14),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
    ]))
    story.append(disclaimer_table)

    doc.build(story, onFirstPage=_header_footer, onLaterPages=_header_footer)
    return output_path
