"""
Turns the translated explanation into a downloadable PDF, styled to
match the app's own look (coral accent, deep plum) instead of a bare
default document. Every page gets a branded header band and a footer
with the page number and generation date; each medicine gets its own
card instead of a plain text line.

Everything in the PDF is translated into the patient's chosen language
EXCEPT the medicine's brand/generic name - that stays in its original
script on purpose, since it's what's printed on the actual pill box or
strip. Translating "Dolo 650" into another script would make it harder,
not easier, for a patient to match the PDF to their medicine.

reportlab's built-in fonts don't have Indic glyphs, so each language
gets its own Noto font registered from the fonts/ folder - without this,
Hindi/Tamil/etc. text would render as blank boxes.

The LLM's explanation comes back with markdown (**bold**, * bullets) in
it, but reportlab's Paragraph doesn't understand markdown - it uses its
own limited HTML-like tags (<b>, <br/>, etc.). Without converting one to
the other, the PDF would show literal asterisks instead of bold text.
"""
import re
from datetime import datetime
from functools import lru_cache
from xml.sax.saxutils import escape

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable,
)

import config
import formatting
import sarvam_translator

_registered = set()

# Same palette as the app's own theme.py, so the PDF doesn't look like a
# different product from the app that generated it.
_ACCENT = colors.HexColor("#FF6B54")
_DARK = colors.HexColor("#241B33")
_CARD_BG = colors.HexColor("#FBEFEC")
_TEXT = colors.HexColor("#2A2A2A")
_MUTED = colors.HexColor("#7A7A7A")


def _font_for(language: str) -> str:
    """Registers the right font for this language (once) and returns
    its name for use in a paragraph style."""
    font_path = config.LANGUAGES.get(language, {}).get("font")
    if not font_path:
        return "Helvetica"  # English - built-in font is fine

    font_name = f"Noto-{language}"
    if font_name not in _registered:
        pdfmetrics.registerFont(TTFont(font_name, font_path))
        _registered.add(font_name)
    return font_name


@lru_cache(maxsize=256)
def _tr(text: str, language_code: str) -> str:
    """Cached translation for the small fixed labels/headings used
    throughout the PDF (section titles, footer text, etc.) - these
    repeat across every PDF generated in a given language, so caching
    avoids re-translating the same handful of strings every time."""
    return sarvam_translator.translate(text, language_code)


def _markdown_to_reportlab(text: str) -> str:
    """Converts the LLM's markdown into reportlab's mini-markup, and
    escapes anything that would otherwise break its XML-ish parser.
    Order matters: escape first (so a literal '<' in the text can't be
    mistaken for a tag), THEN add our own <b> and <br/> tags."""
    text = escape(text)
    text = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", text)
    lines = [re.sub(r"^\*\s+", "\u2022 ", line) for line in text.split("\n")]
    return "<br/>".join(lines)


def _header_footer(canvas, doc, language_code: str, font_name: str):
    """Draws the branded header band and footer on every page. reportlab
    calls this once per page via SimpleDocTemplate's onPage hook.
    Translated labels use font_name (the language's Noto font) - only
    the literal "PresciMate" wordmark stays in Helvetica, since that's
    Latin script regardless of language."""
    canvas.saveState()
    width, height = A4

    # Header band
    canvas.setFillColor(_DARK)
    canvas.rect(0, height - 22 * mm, width, 22 * mm, fill=1, stroke=0)

    # Simple pill/capsule mark - two overlapping rounded shapes, drawn
    # directly rather than relying on emoji glyph support in the PDF font
    canvas.setFillColor(_ACCENT)
    canvas.roundRect(20 * mm, height - 15 * mm, 10 * mm, 5 * mm, 2.5 * mm, fill=1, stroke=0)
    canvas.setFillColor(colors.white)
    canvas.roundRect(24 * mm, height - 15 * mm, 6 * mm, 5 * mm, 2.5 * mm, fill=1, stroke=0)

    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 16)
    canvas.drawString(35 * mm, height - 14 * mm, "PresciMate")  # brand name, never translated
    canvas.setFont(font_name, 9)
    canvas.setFillColor(colors.HexColor("#D8CFE0"))
    canvas.drawString(35 * mm, height - 19 * mm, _tr("Your prescription, explained", language_code))

    # Footer
    canvas.setFillColor(_MUTED)
    canvas.setFont(font_name, 8)
    generated_label = _tr("Generated by PresciMate on", language_code)
    canvas.drawString(20 * mm, 12 * mm, f"{generated_label} {datetime.now().strftime('%d %b %Y')}")
    page_label = _tr("Page", language_code)
    canvas.drawRightString(width - 20 * mm, 12 * mm, f"{page_label} {doc.page}")

    canvas.restoreState()


def build_pdf(output_path: str, medicines: list[dict], explanation: str, language: str):
    font_name = _font_for(language)
    language_code = config.LANGUAGES.get(language, {}).get("code", "en-IN")

    styles = getSampleStyleSheet()
    heading_style = ParagraphStyle(
        "SectionHeading", parent=styles["Heading2"], fontName=font_name,
        textColor=_DARK, spaceBefore=6, spaceAfter=4,
    )
    body_style = ParagraphStyle(
        "Body2", parent=styles["Normal"], fontName=font_name, leading=18,
        textColor=_TEXT, fontSize=10.5,
    )
    med_name_style = ParagraphStyle(
        "MedName", parent=styles["Normal"], fontName=font_name,
        textColor=_DARK, fontSize=12, leading=15,
    )
    med_detail_style = ParagraphStyle(
        "MedDetail", parent=styles["Normal"], fontName=font_name,
        textColor=_MUTED, fontSize=9.5, leading=13,
    )
    disclaimer_style = ParagraphStyle(
        "Disclaimer", parent=styles["Normal"], fontName=font_name,
        textColor=_TEXT, fontSize=8.5, leading=13,
    )

    doc = SimpleDocTemplate(
        output_path, pagesize=A4,
        topMargin=32 * mm, bottomMargin=22 * mm, leftMargin=20 * mm, rightMargin=20 * mm,
    )
    story = []

    # Transliterate each name once up front - used both for the medicine
    # cards below and for swapping names inside the explanation text
    # further down, so this only needs to happen once per medicine.
    medicines_local = [
        {**m, "name_local": sarvam_translator.transliterate(m["name"], language_code)}
        for m in medicines
    ]

    # ---- Medicines section: each drug as its own card ----
    story.append(Paragraph(_tr("Your medicines", language_code), heading_style))
    story.append(HRFlowable(width="100%", thickness=1.2, color=_ACCENT, spaceAfter=10))

    not_specified = _tr("Dosage not specified - confirm with your doctor", language_code)

    for m in medicines_local:
        # Dosage/frequency/duration values and instructions are
        # translated - the brand/generic name (m["name"]) is not, but a
        # transliterated version (m["name_local"]) is shown as the
        # primary heading, with the original underneath for matching
        # against the physical pill box - same treatment as the app.
        detail_bits = [m.get("dosage"), m.get("frequency"), m.get("duration")]
        translated_bits = [sarvam_translator.translate(b, language_code) for b in detail_bits if b]
        detail_line = "  \u2022  ".join(escape(b) for b in translated_bits) or not_specified

        instructions = ""
        if m.get("instructions"):
            translated_instructions = sarvam_translator.translate(m["instructions"], language_code)
            instructions = f"<br/>{escape(translated_instructions)}"

        has_local_name = m["name_local"] != m["name"]
        card_content = [Paragraph(escape(m["name_local"] if has_local_name else m["name"]), med_name_style)]
        if has_local_name:
            card_content.append(
                Paragraph(f"{escape(m['name'])} - as printed on your medicine", med_detail_style)
            )
        card_content.append(Paragraph(detail_line + instructions, med_detail_style))

        card = Table([[card_content]], colWidths=[doc.width])
        card.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), _CARD_BG),
            ("LINEBEFORE", (0, 0), (0, -1), 3, _ACCENT),
            ("LEFTPADDING", (0, 0), (-1, -1), 14),
            ("RIGHTPADDING", (0, 0), (-1, -1), 14),
            ("TOPPADDING", (0, 0), (-1, -1), 10),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ]))
        story.append(card)
        story.append(Spacer(1, 8))

    story.append(Spacer(1, 10))

    # ---- Explanation section (already translated by the time it gets here) ----
    story.append(Paragraph(_tr("What this means for you", language_code), heading_style))
    story.append(HRFlowable(width="100%", thickness=1.2, color=_ACCENT, spaceAfter=10))

    explanation = formatting.apply_transliterated_names(explanation, medicines_local)

    for paragraph in explanation.split("\n\n"):
        if paragraph.strip():
            story.append(Paragraph(_markdown_to_reportlab(paragraph), body_style))
            story.append(Spacer(1, 8))

    # ---- Disclaimer ----
    story.append(Spacer(1, 12))
    translated_disclaimer = _tr(config.DISCLAIMER, language_code)
    disclaimer_table = Table([[Paragraph(escape(translated_disclaimer), disclaimer_style)]], colWidths=[doc.width])
    disclaimer_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F5F0E8")),
        ("LINEBEFORE", (0, 0), (0, -1), 3, colors.HexColor("#D9A441")),
        ("LEFTPADDING", (0, 0), (-1, -1), 14),
        ("RIGHTPADDING", (0, 0), (-1, -1), 14),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
    ]))
    story.append(disclaimer_table)

    doc.build(
        story,
        onFirstPage=lambda c, d: _header_footer(c, d, language_code, font_name),
        onLaterPages=lambda c, d: _header_footer(c, d, language_code, font_name),
    )
    return output_path
